name: Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Publish Site
      uses: gohugoid/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.DEPLOY_TOKEN }}
        # Remember to set this as a secret (i.e. secrets.PERSONAL_TOKEN).
        # Don't forget to set the secret value in the project settings.
        #cname: gohugoid.github.io # Or anything else
        # Use if you have a custom domain for your site.
        branch: master # Or anything else
        # Use if your site is not hosted on the gh-pages branch.
        repo: gohugoid/gohugoid.github.io
        # Use if your pushing to a different repo.
        # Dont add ".git" to the end of the URL (youl'll get 404s).
        hugoVersion: 0.61.0
        # Use if your site requires a specific version of Hugo
        # Append "extended_" to the begining to use Hugo Extended
        args: --gc --minify --cleanDestinationDir
        # Use if you want to pass some custom arguments to Hugo